config/routes.rb
Rails.application.routes.draw do
  root controller: :pages, action: :home
  devise_for :users

  resources :chunks
  resources :chunk_feeds
  resources :room_messages
  resources :rooms

  get '/users/sign_out', controller: :pages, action: :home
  get '/chat', controller: :rooms, action: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chunk.rb
class Chunk < ApplicationRecord
  validates :title, presence: true
  validates :duration, presence: true, numericality: { only_integer: true }

  belongs_to :user, optional: true, inverse_of: :chunks
  belongs_to :chunk_feed, optional: true, inverse_of: :chunks

  def completed?
    Time.now > (created_at + duration.minutes)
  end

  def seconds_to_completion
    ((created_at + duration.minutes) - Time.now) / 3600
  end

  def completion_at
    created_at + duration.minutes
  end
end

app/models/chunk_feed.rb
class ChunkFeed < ApplicationRecord
  belongs_to :user
  has_many :chunks

  def head
    chunks.max_by(&:created_at)
  end

  def tail
    _head, *tail = chunks.sort_by(&:created_at).reverse!
    tail
  end

  def sorted
    chunks.sort_by(&:created_at).reverse!
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_messages, dependent: :destroy, inverse_of: :room
end

app/models/room_message.rb
class RoomMessage < ApplicationRecord
  belongs_to :room
  belongs_to :user, inverse_of: :room_messages

  def as_json(options)
    super(options).merge(testy: 'test')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :chunk_feed
  has_many :chunks, inverse_of: :user
  has_many :room_messages

  # gotta convert this to a SQL query at some point
  # also, this will not scale
  # gotta write some stress tests
  def chunking?
    chunks.inject(false) do |status, chunk|
      status || Time.now < (chunk.created_at + chunk.duration.minutes)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chunk_feeds_controller.rb
class ChunkFeedsController < ApplicationController
  before_action :load_entities

  def index
    @chunk_feed
  end

  def show
    @chunk = Chunk.new(chunk_feed: @chunk_feed)
    @chunks = @chunk_feed.chunks.includes(:user)
    respond_to do |format|
      format.html
      format.json { render json: @chunk_feed }
    end
  end

  def update
  end

  protected

  def load_entities
    @chunk_feed = ChunkFeed.find_by(user: current_user)
  end
end

app/controllers/chunks_controller.rb
class ChunksController < ApplicationController
  before_action :load_entities

  def create
    @chunk = Chunk.create user: current_user,
                          chunk_feed: @chunk_feed,
                          title: params[:title],
                          duration: params[:duration]

    if @chunk.save
      duration = params[:duration].to_i
      CompleteChunkJob.set(wait: duration.minutes).perform_later(@chunk)
    else
      puts 'TODO'
    end

    ChunkFeedChannel.broadcast_to(@chunk_feed, @chunk)
  end

  protected

  def load_entities
    @chunk_feed = ChunkFeed.find(params.dig(:chunk_feed_id))
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @chunk_feed = current_user.chunk_feed if current_user
    @chunk = Chunk.new
  end
end

app/controllers/room_messages_controller.rb
class RoomMessagesController < ApplicationController
  before_action :load_entities

  def create
    @room_message = RoomMessage.create user: current_user,
                                       room: @room,
                                       message: params.dig(:message)

    RoomChannel.broadcast_to(@room, @room_message)
  end

  protected

  def load_entities
    @room = Room.find params.dig(:room_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :load_entities

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new permitted_parameters

    if @room.save
      flash[:success] = "Room #{@room.name} was created successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @room.update_attributes(permitted_parameters)
      flash[:success] = "Room #{@room.name} was updated successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end

  def show
    @room_message = RoomMessage.new room: @room
    @room_messages = @room.room_messages.includes(:user)
    respond_to do |format|
      format.html
      format.json { render json: @room }
    end
  end

  protected

  def load_entities
    @rooms = Room.all
    @room = Room.find(params[:id]) if params[:id]
  end

  def permitted_parameters
    params.permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chunk_feeds_helper.rb
module ChunkFeedsHelper
end

app/helpers/room_messages_helper.rb
module RoomMessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/chunk_feeds/_chunking.html.erb
<ul id='chunk-feed-container' style="list-style: none">
  <li data-controller="active-chunk" id="active-chunk" class="chunk active-chunk active-chunk--visible ">
    <div data-target="active-chunk.title">Title: <%= current_user.chunk_feed.head.title %></div>
    <div data-target="active-chunk.started-at">Started at: <%= current_user.chunk_feed.head.created_at %></div>
    <div data-target="active-chunk-duration">Duration: <%= current_user.chunk_feed.head.duration %></div>
    <div>Chunk in Progress</div>
    <div>Completion at: <%= current_user.chunk_feed.head.completion_at %></div>
  </li>

  <% current_user.chunk_feed.tail.each do |chunk| %>
    <%= render partial: './chunks/show', locals: { chunk: chunk } %>
  <% end %>
<ul>

app/views/chunk_feeds/_not_chunking.html.erb
<ul id='chunk-feed-container' style="list-style: none">
  <li data-controller="active-chunk" id="active-chunk" class="chunk active-chunk">
    <div>Chunk in Progress</div>
    <div>Completion at: <%= @chunk_feed.head.completion_at %></div>

    <div>
      <span>Title: </span>
      <span><%= chunk.title %></span>
    </div>

    <div>
      <span>Started at: </span>
      <span><%= chunk.created_at %></span>
    </div>

    <div>
      <span>Duration: </span>
      <span><%= chunk.duration %></span>
    </div>
  </li>

  <% current_user.chunk_feed.sorted.each do |chunk| %>
    <%= render partial: './chunks/show', locals: { chunk: chunk } %>
  <% end %>
<ul>

app/views/chunk_feeds/_show.html.erb
<section data-controller='chunk-feed'>
  <% if current_user %>
    <%= hidden_field_tag :chunk_feed_id, @chunk_feed.id, id: 'chunk-feed-id' %>

    <%= render partial: './chunks/new' %>

    <ul data-target='chunk-feed.container' id='chunk-feed-container' style="list-style: none">
      <% @chunk_feed.sorted.each do |chunk| %>
        <%= render partial: './chunks/show', locals: { chunk: chunk } %>
      <% end %>
    </ul>
  <% end %>
</section>

app/views/chunk_feeds/show.html.erb
<section>
  <% if current_user %>
    <h3 id="testy">Chunks</h3>
    <ul id='chunks-list' style="list-style: none">
      <% current_user.chunks.reverse.each do |c| %>
        <li style="margin: 20px" id=<%= c.id %>>
          <div>Title: <%= c.title %></div>
          <div>Started at: <%= c.created_at.in_time_zone("Central Time (US & Canada)").strftime("%H:%M on %m/%d/%Y") %></div>
          <div>Duration: <%= c.duration %></div>

          <div><% e = c.created_at + c.duration.minutes %></div>
          <% if Time.now >= e %>
            <div>Chunk Completed</div>
          <% else %>
            <div>Chunk in Progress</div>
            <div>Completion at <%= e.in_time_zone("Central Time (US & Canada)").strftime("%H:%M") %></div>
          <% end %>
        </li>
      <% end %>
    </ul>
  <% end %>
</section>

app/views/chunks/_active_chunk.html.erb
 <li data-controller="active-chunk" id="active-chunk" class="chunk active-chunk <%= cssClass %>">
    <div>
      <h3 data-target="active-chunk.status">Chunk in Progress</h3>
      <span data-target="active-chunk.completion-at">Completion at: <%= @chunk_feed.head.completion_at %></span>
    </div>

    <div>
      <span>Title: </span>
      <span data-target="active-chunk.title"><%= chunk.title %></span>
    </div>

    <div>
      <span>Started at: </span>
      <span data-target="active-chunk.started-at"><%= chunk.created_at %></span>
    </div>

    <div>
      <span>Duration: </span>
      <span data-target="active-chunk-duration"><%= chunk.duration %></span>
    </div>
  </li>

app/views/chunks/_new.html.erb
<section>
  <% if current_user.chunking? %>
    <% user_status = "block" %>
    <% new_chunk = "none" %>
  <% else %>
    <% user_status = "none" %>
    <% new_chunk = "block" %>
  <% end %>

  <h3 data-target="chunk-feed.userStatus" style='display: <%= user_status %>'>You are currently chunking</h3>

  <div data-target="chunk-feed.newChunk" style='display: <%= new_chunk %>'>
    <%= form_for @chunk, url: { controller: "chunks", action: "create" },
                        html: { onsubmit: "this.submit(); this.reset();" },
                        data: { remote: true } do |f| %>

      <%= label_tag(:title, "Title") %>
      <%= text_field_tag(:title, nil, { id: "title",
                                        data: { target: "chunk-feed.title" } }) %>

      <%= label_tag(:duration, "How long will the chunk be?") %>
      <%= number_field_tag(:duration, nil, { step: 1,
                                        data: { target: "chunk-feed.duration" } }) %>

      <%= hidden_field_tag(:chunk_feed_id, current_user.chunk_feed.id) %>

      <%= f.submit "Create Chunk", data: { action: "chunk-feed#create" } %>
    </div>
  <% end %>
</section>

app/views/chunks/_show.html.erb
<li class="chunk" id=<%= chunk.id %> >
  <% if chunk.completed? %>
    <div>
      <h3 data-target="chunk-feed.chunkStatus">Chunk Completed!</h3>
      <span data-target="chunk-feed.completion">Completed at: </span>
      <span><%= chunk.completed_at %></span>
    </div>
  <% else %>
    <div>
      <h3 data-target="chunk-feed.chunkStatus">Chunk in Progress</h3>
      <span data-target="chunk-feed.completion">Completion at: </span>
      <span><%= chunk.completion_at %></span>
    </div>
  <% end %>

  <div>
    <span>Title: </span>
    <span><%= chunk.title %></span>
  </div>

  <div>
    <span>Started at: </span>
    <span><%= chunk.created_at %></span>
  </div>

  <div>
    <span>Duration: </span>
    <span><%= chunk.duration %></span>
  </div>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chunk Master</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render partial: './shared/nav'%>
<%= render partial: './chunk_feeds/show' %>

app/views/rooms/_form.html.erb
<%= form_for @room, :url => { controller: "rooms", action: "create" }  do |f| %>
  <%= label_tag(:name, "Name") %>
  <%= text_field_tag(:name) %>
  <%= f.submit "Create Room" %>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing room <%= room.name %></h1>

<%= render partial: 'form'%>

app/views/rooms/index.html.erb
<h1>CHAT</h1>

<%= link_to new_room_path do %>
  New Room
<% end %>

<div style="margin-top: 1em">
  <% if @rooms.present? %>
    <% @rooms.each do |room| %>
      <%= link_to room.name, room_path(room) %>
    <% end %>
  <% else %>
    No rooms
  <% end %>
</div>

app/views/rooms/new.html.erb
<h1>Creating a room</h1>

<%= render partial: 'form' %>

app/views/rooms/show.html.erb
<h1><<%= @room.name %></h1>

<h3 id="room_id">Room: <%= @room.name %></h3>

<div class="chat" data-channel-subscribe="room" id="room-container">
  <% @room_messages.each do |room_message| %>
    <div id="msg-<%= room_message.id %>"><%= room_message.message %></div>
  <% end %>
</div>

<div style="margin-top: 2em">
  <%= form_for @room_message, :url => { controller: "room_messages", action: "create"}, :data => { :remote => true } do |f| %>
    <%= label_tag(:message, "Message") %>
    <%= text_field_tag(:message) %>
    <%= hidden_field_tag(:room_id, @room.id) %>
    <%= f.submit "Send Message" %>
  <% end %>
</div>

app/views/shared/_nav.html.erb
<h1>Chunk Master</h1>

<section style="margin-bottom: 50px">
  <% if current_user %>
    <div>Welcome, <%= current_user.email  %></div>
    <div>
      <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
    </div>
  <% else %>
    <div>Welcome</div>
    <div>
      <%= link_to 'Sign Up', new_user_registration_path %>
      <%= link_to 'Sign In', user_session_path %>
    </div>
  <% end %>
</section>